<!-- This code essentially sets up a connection to a MySQL database using PHP's mysqli_connect function and checks if the connection was successful. If the connection fails, it displays an error message with the reason for the failure. -->


<?php
$servername = "localhost"; // This line sets the server name or IP address where the MySQL database is hosted.
$username = "root"; // This line sets the MySQL username used to connect to the database.
$password = ""; // This line sets the MySQL password used to authenticate the connection.
$dbname = "suku_db"; // This line sets the name of the MySQL database you want to connect to.

// Create connection
$conn = mysqli_connect($servername, $username, $password, $dbname);
// The above line establishes a connection to the MySQL database using the provided servername, username, password, and database name.

// Check connection
if (!$conn) {
    // This block checks if the connection to the database was unsuccessful.
    // If the connection fails, it will enter this block.
    // It prints an error message along with the specific error message generated by mysqli_connect_error().
    echo ("Connection failed: " . mysqli_connect_error());
}   
?>
